---
title: "Writing Functions"
author: "Keyanna Davis"
date: "10/28/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

We're going to write some functions 

Here's zscores
```{r}
x = rnorm( n = 30, mean = 5, sd = 2.3)

x_again =  rnorm( n = 30, mean = 6, sd = .3)

(x - mean(x)) / sd(x)
```

Now a function 

```{r}
z_score = function(x) {
  
 if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) > 3 ) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  (x-mean(x)) / sd(x)
  
  
}
```


Try out the function
```{r}
#z_score(x=x_again)
#z_score(x=3)
#z_score(x = "my name is Keyanna")
#z_score(x = c(TRUE, TRUE, FALSE, TRUE))
#z_score(x = iris)
```


## Multiple outputs
```{r}
mean_and_sd = function(input_x) {
  if (!is.numeric(input_x)) {
    stop("x should be numeric")
  } else if (length(input_x) < 3) {
    stop("x should be longer than 3")
  }
  list( 
  mean_input = mean(input_x),
  sd_input =sd(input_x),
  z_score = (input_x - mean(input_x)) / sd(input_x)
  )
}
```

test this function

```{r}
mean_and_sd(input_x = x_again)
```

##Multiple inputs

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```


```{r}
sim_regression = function(n, beta0 , beta1) {
  sim_data = tibble(
  x = rnorm(n, mean = 1, sd = 1),
  y = beta0 + beta1 * x + rnorm(n, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)

tibble(  
beta0_hat = coef(ls_fit)[1],
beta1_hat = coef(ls_fit)[2]
)
}

sim_regression(n = 3000, beta0 = 17, beta1 = -3)


sim_regression(3000, 2, 3)
```



##Scrape lot of Napoleon 
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


Now as a function

```{r}
read_page_review = function(page_url)
  dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

reviews
```


```{r}
read_page_review("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=2")
```

```{r}
f = function(x) {
  z = x + y
  z
}

x = 1
y = 2

f(x = x)
```

